# Generated by Django 4.1.3 on 2022-11-15 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='student',
            new_name='students',
        ),
    ]
